### ISSUE TITLE
"stty: stdin isn't a terminal" error message when called in a bash loop

### ISSUE THREAD

**Issue by jvalcke** [NetworkAutomation/jaide#23]
I keep getting a stdin error when calling jaide from the command line

For instance:

ls -l *.cmds | awk '{ print $NF }' | sed 's/.cmds//' | while read router; do `jaide -i     $router -u <username> -p <mypassword> operational $router.cmds` ; done
stty: stdin isn't a terminal
Traceback (most recent call last):
  File "/usr/local/bin/jaide", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/site-packages/jaide/cli.py", line 724, in run
    rows, columns = popen('stty size', 'r').read().split()
ValueError: need more than 0 values to unpack
stty: stdin isn't a terminal
Traceback (most recent call last):
  File "/usr/local/bin/jaide", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/site-packages/jaide/cli.py", line 724, in run
    rows, columns = popen('stty size', 'r').read().split()
ValueError: need more than 0 values to unpack

**Comment by nprintz** [comment]
Yup, that's a bug requiring stdin to be a tty. Modifying line [722 of cli.py](https://github.com/NetworkAutomation/jaide/blob/master/jaide/cli.py#L722) as such should alleviate this issue:

`if os.name == 'posix':`
to:
`if os.name == 'posix' and sys.stdin.isatty():`

This adds the dependency of the `sys` module, which isn't a problem. I'll do some testing with this to make sure elsewhere no other tty dependencies are required (thinking of when using scp operations).

**Comment by nprintz** [comment]
I committed what I hope to be the fix for this, and did some testing with the different jaide commands using this syntax so that stdin wasn't a terminal:

`$ echo | jaide -i <ip> -u <username> -p <password> info`

Would it be possible for you to download the latest source and give this a shot for your bash script? You can `pip uninstall jaide` and then extract the source code and change to its directory before doing `pip install .`
