### ISSUE TITLE
Use DNS Names

### ISSUE THREAD

**Issue by mcparlandj** [NetworkAutomation/jaide#3]
Not sure if I should post this here as an issue as I think it's more of a feature request. I'm not sure how to send a feature request though. 

Under the "IP(S) Host(s):" I can't do DNS names for switches. I can only do IP addresses. When dealing with over 100 switches it would be super helpful for us to be able to use DNS names because then the output would have the DNS name in it. Our DNS names help tell me where a switch is physically located. 
The way it works now is the output gives me the switch IP address and at that point i need to start digging through an excel file to match the IP address with the DNS name, or do a dig in the terminal. 

Not a high priority at all, but this feature would save us a lot of time and be very useful. Thanks so much for the awesome application!

**Comment by nprintz** [comment]
Ah, that's because the input validation in the JGUI is looking for an IP or a file path. You're right, and this shouldn't be so strict, since it eliminates the ability for hostnames. I'll pull out that check in the next version. This will leave the exception handling for establishing a connection in jaide.py to float to JGUI. 

In the meantime, There are two workarounds for this. You can use the command-line tool, as it doesn't have this check, and hostnames will work (I replaced the hostname, but this is a valid command execution): 

    $ python jaide.py -u nprintz -c "show int terse | match lo0" -i device.blah.com
    Password: 
    ==================================================
    Results from device: device.blah.com
    
    > show int terse | match lo0
    lo0                     up    up
    lo0.16384               up    up   inet     127.0.0.1           --> 0/0

You can give the GUI a plain text file with hostnames, and that will work as well, since it passes validation. The nice thing about giving it a file is that you can put comment lines ('#' as the first character in the line) and blank lines. Neither will mess the application up, so you can organize the list of IPs for better human understanding.

Here's an example file:  

    # Main office
    device.blah.com
    
    #non-responsive
    device2.blah.com
    
    #EX 3300 VC
    device3.blah.com
    
    #EX 3300 standalone
    device4.blah.com

Note that we're currently working on a hefty restructure of the module, so the next release might be a bit. We're trying to prepare for the module to be accessible via pip, and increase modularity and reduce redundancies in our code.

**Comment by mcparlandj** [comment]
My co-worker was having issues using the hostnames in a file. I told him that it should work. So I tested entering hostnames into the "IP(S) Host(s):" field which didn't work. 
I think what happened was he borked the text file somehow and I stumbled across the no dns name in the IP / Host field. 
So consider this closed. When we need to push stuff to a bunch of switches we'll use the txt file with the hostnames. That totally solves our problem!

**Comment by nprintz** [comment]
Do you have specific information on what transformations in the file caused it to break? Do you still have the broken file? The reason I ask is if there is something that we're not checking for, we might be able to look for the problem in the future and handle it better.
